### ISSUE TITLE
Checking of instance name lengths

### ISSUE THREAD

**Issue by jazdw** [jmdns/jmdns#13]
It doesn't seem like JmDNS does any instance name length checking. According to RFC 6763 the instance name should be limited to 63 octets after conversion to UTF-8.

Its not something that should be handled in client code as JmDNS can append numbers the instance name when there is a duplicate instance name on the network.

**Comment by melloware** [comment]
@kaikreuzer this was fixed by: https://github.com/jmdns/jmdns/pull/255 and can be closed

**Comment by ViToni** [comment]
Actually #255 doesn't solve this issue. The OP correctly mentions
> name should be limited to 63 octets after conversion to UTF-8.

and
> as JmDNS can append numbers the instance name when there is a duplicate instance name on the network

#255 doesn't handle conversion nor a suffix in case of a name collision.

**Comment by melloware** [comment]
@ViToni it sounds like there are 2 different issues in this one ticket

- [ ] The 63 octet limit
- [ ] The collision check
